"""migrate ids to uuid

Revision ID: f3277cefc74e
Revises: c63a5043c647
Create Date: 2026-06-02 06:40:47.119177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3277cefc74e'
down_revision: Union[str, Sequence[str], None] = 'c63a5043c647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop FK constraints first
    op.drop_constraint('stock_movements_product_id_fkey', 'stock_movements', type_='foreignkey')
    op.drop_constraint('products_owner_id_fkey', 'products', type_='foreignkey')

    # Alter columns
    op.alter_column('users', 'id', existing_type=sa.INTEGER(), type_=sa.String(length=36), existing_nullable=False)
    op.alter_column('products', 'id', existing_type=sa.INTEGER(), type_=sa.String(length=36), existing_nullable=False)
    op.alter_column('products', 'owner_id', existing_type=sa.INTEGER(), type_=sa.String(length=36), existing_nullable=False)
    op.alter_column('stock_movements', 'id', existing_type=sa.INTEGER(), type_=sa.String(length=36), existing_nullable=False)
    op.alter_column('stock_movements', 'product_id', existing_type=sa.INTEGER(), type_=sa.String(length=36), existing_nullable=False)

    # Recreate FK constraints
    op.create_foreign_key('products_owner_id_fkey', 'products', 'users', ['owner_id'], ['id'])
    op.create_foreign_key('stock_movements_product_id_fkey', 'stock_movements', 'products', ['product_id'], ['id'], ondelete='CASCADE')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_index(op.f('ix_stock_movements_id'), 'stock_movements', ['id'], unique=False)
    op.alter_column('stock_movements', 'product_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('stock_movements', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.alter_column('products', 'owner_id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('products', 'id',
               existing_type=sa.String(length=36),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
